---
title: Reformation
timezone: UTC
collections:
  notes:
    title: Notes
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    excerpt: 
    description: 
    image: 
    video: 
    is-featured: 
    images:
    - image: 
      caption: 
    discipline: 
    format:
    - 
    layout: page
url: https://www.reformation.studio
description: Reformation is a London based graphic design studio specializing in visual identities, websites and printed matter.
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
company: Reformation
company-address: Office 5, Unit R1, Penfold Works, Imperial Way, Watford, WD24 4YY
email: hello@reformation.studio
analytics:
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %Y"
future: true
social: 
clients:
  bbc: https://www.bbc.co.uk
  conde-nast: https://www.condenast.co.uk
  nike: https://www.nike.com
  refinery-29: https://www.refinery29.com
  the-guardian: https://www.theguardian.com
  the-new-york-times: https://www.nytimes.com
  vice: https://www.vice.com
  youtube: https://www.universalpictures.com
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  collection: posts
  enabled: true
  per_page: 6
  limit: 0
  permalink: "/:num/"
  title: ":title — :num of :max"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: false
imgix:
  source: reformation.imgix.net