app: glowing
ssh_url: glowing@deploy.us1.frbit.com
ssh_path: null
git_remote: glowing/master
before:
    code/up:
        - 'echo  "Script example: " $(git rev-parse HEAD)'
after:
    code/down:
        - 'php craft migrate/all'
